### PR TITLE
Full DI support via init

### PR DESCRIPTION
**Pull request by davidfhaines**

### CODE REVIEW

**Comment by cmartin81** [comment]
I have given you rights to commit directly into the project.

**Comment by cmartin81** [comment]
I'm away from the Mac for the next 8hours

**Comment by davidfhaines** [comment]
No worries. I'll drop this PR and commit directly.

**Comment by cmartin81** [comment]
Great! Remember to run the gulp task before you commit.

Den lørdag 17. oktober 2015 skrev David Haines notifications@github.com
følgende:

**Comment by davidfhaines** [comment]
That should be sorted. Would you mind adding polyglotted as a contributor to the npm package so I may publish as well?

**Comment by cmartin81** [comment]
Done :)

**Comment by cmartin81** [comment]
I've been using this package for 6 months now, but only the controller and
factory decorators. (not the services or in this case the dervices
decorator). Thanks for spotting the error and fixing it.

**Comment by davidfhaines** [comment]
Much obliged Christian. This little utility is great. Thanks for making it! :)

**Pull request closed without merging**
